# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 014c111832772cf4d341dbe6f3242b47630b1c806442a6f7537779ceab882028a6ba6a880e25e6d0d094e4302a01047aa0ed74fb28dc4a96f79080702181be32

test:
  secret_key_base: 7f07e07130e6f7ef4750667b866164d58fb99db5f0d1c30f72bda94435585fb4604c8dfbd3c82b8d6689d9e9bf197cc778b374e79a4b04a7719f295450b5f4da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
